### ISSUE TITLE
Ignore a field on serialization not working as intended

### ISSUE THREAD

**Issue by kvpt** [SimonCropp/Argon#329]
Hi,

I encounter a serialization issue in a test that use Verify which use this library to serialize data.

I have a field that I want to ignore and it doesn't seem to work.

From the [documentation](https://github.com/SimonCropp/Argon/blob/main/docs/SerializationAttributes.md#jsonignoreattribute), there is two ways to ignore a field, by using JsonIgnore or NonSerialized attribute.

I have tested the two options and reproduced it in this simple snippet :

``` cs
void Main()
{
	var product = new Data
	{
	    Name = "Test",
	    Private = "Private"
	};
	
	var json = Argon.JsonConvert.SerializeObject(product);
	
	json.Dump();
}

[Serializable]
public class Data
{
        public string Name { get; set; }
	
	[NonSerialized]
	[JsonIgnore]
	public string Private;
}
```

By searching in the code I have found that IgnoreDataMember attribute is also checked and this seems to work, but it's not documented so I don't known if it's intended to work that way or not.

**Comment by SimonCropp** [comment]
happy to consider a pull request  that fixes this
